services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        
    MetinBaris\InventoryBundle\Command\ReadInventoryCommand:
        arguments:
            $inventoryCsvService: '@MetinBaris\InventoryBundle\Service\InventoryCsvService'
        tags:
            - { name: 'console.command' }

    MetinBaris\InventoryBundle\Service\InventoryCsvService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    MetinBaris\InventoryBundle\Service\InventoryProcessor:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $bus: '@messenger.default_bus'

    MetinBaris\InventoryBundle\Controller\InventoryController:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $inventoryProcessor: '@MetinBaris\InventoryBundle\Service\InventoryProcessor'
        tags:
            - { name: 'controller.service_arguments' }
        public: true

    MetinBaris\InventoryBundle\MessageHandler\InventoryOutOfStockMessageHandler:
        tags:
            - { name: messenger.message_handler, method: __invoke, bus: messenger.bus.default }
        arguments:
            $mailer: '@mailer'

doctrine:
    orm:
        mappings:
            InventoryBundle:
                is_bundle: true
                type: attribute
                dir: 'Entity'
                prefix: 'MetinBaris\InventoryBundle\Entity'
                alias: InventoryBundle
